services:
  postgres:
    container_name: JobListing_postgres
    image: postgres:14.3
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - JobListing_postgres:/var/lib/postgresql/data
volumes:
  JobListing_postgres: